version: '3'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
<<<<<<< HEAD
      - DATABASE_URL=postgresql://postgres:SayMyName@db:5432/postgres

=======
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOSTNAME=db
    # depends_on:
    #   - db
    networks:
      - my-network
>>>>>>> bfffcc8188baa7e98df7784c1f4b2bbeb9f92d59
    

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SayMyName
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /path/to/db/data:/var/lib/postgresql/data
    networks:
      - my-network



  
  frontend:
    build:
      context: ./SayMyNameProjectFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - my-network
    # depends_on:
    #   - app
  
networks:
  my-network:
    driver: bridge
