version: '3'

services:
  app:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOSTNAME=db
    depends_on:
      - db
    

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /path/to/db/data:/var/lib/postgresql/data

  
  frontend:
    build: ./SayMyName_frontend/SYM/SayMyNameProjectFrontend
    ports:
      - "4200:4200"
    depends_on:
      - app
