# Use the latest Node.js LTS image as the base image
FROM node:20 as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Install @angular-devkit/build-angular package
RUN npm install --save-dev @angular-devkit/build-angular

# Copy the entire project to the container
COPY . .

# Expose port 4200 (assuming your Angular app runs on this port)
EXPOSE 4200

# Command to start the Angular development server
CMD ["npm", "start"]